/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeleteStudentModa: typeof import('./src/components/delete-student-moda.vue')['default']
    DeleteStudentModal: typeof import('./src/components/delete-student-modal.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/side-bar.vue')['default']
    StudentTable: typeof import('./src/components/student-table.vue')['default']
    StudentToolbar: typeof import('./src/components/student-toolbar.vue')['default']
    TableActions: typeof import('./src/components/table-actions.vue')['default']
  }
}
